import {
  Activity,
  ArrowRight,
  Award,
  BarChart2,
  Calendar,
  Check,
  ChevronLeft,
  ChevronRight,
  Clock,
  Code,
  Code2,
  Command,
  CreditCard,
  File,
  FileText,
  Flame,
  Folder,
  Github,
  GitBranch,
  GitCommit,
  GitFork,
  GitMerge,
  GitPullRequest,
  Heart,
  History,
  Home,
  Image,
  Info,
  Laptop,
  Layout,
  LifeBuoy,
  Link,
  List,
  Lock,
  LucideIcon,
  LucideProps,
  Mail,
  MessageSquare,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Package,
  PanelLeft,
  PanelLeftOpen,
  PanelRight,
  PanelRightOpen,
  PlusCircle,
  PlusSquare,
  RefreshCw,
  Search,
  Settings,
  Share,
  SidebarClose,
  SidebarOpen,
  Smile,
  Star,
  Sun,
  Terminal,
  ThumbsUp,
  Timer,
  Trash,
  Trophy,
  Twitter,
  Upload,
  User,
  UserPlus,
  Users,
  X,
  AlertCircle
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  logo: Command,
  close: X,
  settings: Settings,
  spinner: RefreshCw,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  activity: Activity,
  star: Star,
  code: Code,
  code2: Code2,
  flame: Flame,
  gitCommit: GitCommit,
  gitPullRequest: GitPullRequest,
  gitBranch: GitBranch,
  gitMerge: GitMerge,
  gitFork: GitFork,
  github: Github,
  twitter: Twitter,
  user: User,
  users: Users,
  plus: PlusCircle,
  arrowRight: ArrowRight,
  help: Info,
  lock: Lock,
  panel: LayoutIcon,
  trophy: Trophy,
  award: Award,
  folder: Folder,
  file: File,
  fileText: FileText,
  clock: Clock,
  calendar: Calendar,
  layout: Layout,
  dashboard: LayoutIcon,
  smile: Smile,
  heart: Heart,
  mail: Mail,
  image: Image,
  thumbsUp: ThumbsUp,
  share: Share,
  barChart: BarChart2,
  history: History
}

function LayoutIcon(props: LucideProps) {
  return (
    <div className="icon layout">
      <Layout {...props} />
    </div>
  )
} 